### ISSUE TITLE
Verwendung unter Contao 3.5.34 noch möglich?

### ISSUE THREAD

**Issue by denniserdmann** [cliffparnitzky/BirthdayLister#6]
Moin!
Ich wollte die Erweiterung unter Contao 3.5.34 testen, nach der Installation und der Aktualisierung der Datenbank, bekomme ich beim Versuch, ein FE-Modul anzulegen folgenden Fehler:

```
[20-Mar-2018 11:10:14 GMT] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Field 'birthdayListMemberGroups' doesn't have a default value (INSERT INTO tl_module (type, cols, queryType, contextLength, totalLength, perPage, searchType, inColumn, source, rss_cache, rss_template, numberOfItems, cal_startDay, cal_format, cal_order, cal_template, cal_ctemplate, com_order, com_template, list_layout, list_info_layout, news_featured, news_metaFields, news_template, news_format, news_startDay, news_order, nl_template, pid, tstamp) VALUES ('navigation', '2cl', 'and', 48, 1000, 0, 'simple', 'main', 'internal', 3600, 'rss_default', 3, 1, 'cal_month', 'ascending', 'event_full', 'cal_default', 'ascending', 'com_default', 'list_default', 'info_default', 'all_items', 'a:2:{i:0;s:4:\"date\";i:1;s:6:\"author\";}', 'news_latest', 'news_month', 0, 'descending', 'nl_simple', '1', 0))' thrown in /Users/[username]/Sites/demos/contao-3.5/project/system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /Users/[username]/Sites/demos/contao-3.5/project/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /Users/[username]/Sites/demos/contao-3.5/project/system/modules/core/drivers/DC_Table.php(689): Contao\Database\Statement->execute()
#2 /Users/[username]/Sites/demos/contao-3.5/project/system/modules/core/classes/Backend.php(650): Contao\DC_Table->create()
#3 /Users/[username]/Sites/demos/contao-3.5/project/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('themes')
#4 /Users/[username]/Sites/demos/contao-3.5/project/contao/main.php(20): Contao\BackendMain->run()
#5 {main}
```

Ich habe eine blanke Contao Installation verwendet.

**Comment by cliffparnitzky** [comment]
In neueren MySQL Versionen (oder auch anderen Datenbanksystemen) ist der Umgang von `NOT NULL` Spalten ohne default Wert viel strikter.

In der Definition für das Feld "birthdayListMemberGroups" muss die SQL Anweisung deshalb so angepasst werden, dass entweder ein default Wert angegeben wird, oder das `NOT NULL` entfernt wird.

siehe: https://github.com/cliffparnitzky/BirthdayLister/blob/master/system/modules/BirthdayLister/dca/tl_module.php#L92

**Comment by denniserdmann** [comment]
Okay, danke. Habe es mit dem Hinweis hinbekommen.
